title: In the world of entertaining pressure
author: Volkova Anastasiia
email: nastyavolkovasoc412@yandex.ru
description: > # this means to ignore newlines until "baseurl:"
  I am 23 years old nerd who is really fascinated by data analysis.

# social links
github_username:  mibisako

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
